### ISSUE TITLE
Feature Request: Unpack image

### ISSUE THREAD

**Issue by pwFoo** [blacktop/graboid#1]
First... graboid is a great tool! Thanks for that!

Would it possible to add a unpack image function or do you know a (small) binary to do that job?

I try to use docker images for example to run with runc or other runtimes...

**Comment by pwFoo** [comment]
Would be really nice to have a small tool to pull and unpack docker images. Additional extract the config file from image too...

**Comment by blacktop** [comment]
What do you mean by unpack?

**Comment by blacktop** [comment]
Do you mean extract files from within?  I don't understand the runc comment in the context of unpacking either?

**Comment by pwFoo** [comment]
I mean extract / unpack the filesystem from an docker image to a directory. It isn't just untar the archive because of layers to apply. So download and extract docker images would be nice.

**Comment by blacktop** [comment]
something like this: https://github.com/blacktop/graboid#extract-a-file-from-the-images-filesystem-construction-new 
# 🤔
